/**
 * Songs - Popular songs for piano practice
 * Each song is broken down into note sequences for step-by-step learning
 */

const SONGS = [
    {
        id: 'twinkle',
        title: 'Twinkle Twinkle Little Star',
        artist: 'Tradicional',
        difficulty: 1,
        key: 'Do Mayor',
        description: 'La primera canción que aprende todo pianista. Melodía simple con repetición.',
        sequence: [
            // Twinkle twinkle little star
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'A', octave: 4 },
            { note: 'A', octave: 4 },
            { note: 'G', octave: 4 },
            // How I wonder what you are
            { note: 'F', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
            // Up above the world so high
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            // Like a diamond in the sky
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            // Twinkle twinkle little star
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'A', octave: 4 },
            { note: 'A', octave: 4 },
            { note: 'G', octave: 4 },
            // How I wonder what you are
            { note: 'F', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
        ]
    },
    {
        id: 'mary-lamb',
        title: 'Mary Had a Little Lamb',
        artist: 'Tradicional',
        difficulty: 1,
        key: 'Do Mayor',
        description: 'Canción clásica para principiantes. Usa solo 4 notas diferentes.',
        sequence: [
            // Mary had a little lamb
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            // Little lamb, little lamb
            { note: 'D', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            // Mary had a little lamb
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            // Its fleece was white as snow
            { note: 'D', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
        ]
    },
    {
        id: 'ode-to-joy',
        title: 'Oda a la Alegría',
        artist: 'Beethoven',
        difficulty: 2,
        key: 'Do Mayor',
        description: 'El famoso tema de la 9ª Sinfonía de Beethoven. Una melodía que todo el mundo conoce.',
        sequence: [
            // Line 1
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            // Line 2
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'D', octave: 4 },
            // Line 3
            { note: 'E', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            // Line 4
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
        ]
    },
    {
        id: 'fur-elise-intro',
        title: 'Para Elisa (Intro)',
        artist: 'Beethoven',
        difficulty: 3,
        key: 'La Menor',
        description: 'Los primeros compases de la obra más famosa de Beethoven. Incluye teclas negras.',
        sequence: [
            { note: 'E', octave: 5 },
            { note: 'D#', octave: 5 },
            { note: 'E', octave: 5 },
            { note: 'D#', octave: 5 },
            { note: 'E', octave: 5 },
            { note: 'B', octave: 4 },
            { note: 'D', octave: 5 },
            { note: 'C', octave: 5 },
            { note: 'A', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'A', octave: 4 },
            { note: 'B', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'G#', octave: 4 },
            { note: 'B', octave: 4 },
            { note: 'C', octave: 5 },
            { note: 'E', octave: 4 },
            { note: 'E', octave: 5 },
            { note: 'D#', octave: 5 },
            { note: 'E', octave: 5 },
            { note: 'D#', octave: 5 },
            { note: 'E', octave: 5 },
            { note: 'B', octave: 4 },
            { note: 'D', octave: 5 },
            { note: 'C', octave: 5 },
            { note: 'A', octave: 4 },
        ]
    },
    {
        id: 'happy-birthday',
        title: 'Cumpleaños Feliz',
        artist: 'Tradicional',
        difficulty: 2,
        key: 'Do Mayor',
        description: 'La canción más cantada del mundo. Sorprende a alguien tocándola en piano.',
        sequence: [
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'C', octave: 4 },
            { note: 'C', octave: 5 },
            { note: 'A', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'A#', octave: 4 },
            { note: 'A#', octave: 4 },
            { note: 'A', octave: 4 },
            { note: 'F', octave: 4 },
            { note: 'G', octave: 4 },
            { note: 'F', octave: 4 },
        ]
    },
    {
        id: 'canon-melody',
        title: 'Canon en Re (Melodía)',
        artist: 'Pachelbel',
        difficulty: 3,
        key: 'Re Mayor',
        description: 'La melodía principal del Canon de Pachelbel. Usa sostenidos (Fa# y Do#).',
        sequence: [
            { note: 'F#', octave: 4 },
            { note: 'E', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C#', octave: 4 },
            { note: 'B', octave: 3 },
            { note: 'A', octave: 3 },
            { note: 'B', octave: 3 },
            { note: 'C#', octave: 4 },
            { note: 'D', octave: 4 },
            { note: 'C#', octave: 4 },
            { note: 'B', octave: 3 },
            { note: 'A', octave: 3 },
            { note: 'G', octave: 3 },
            { note: 'F#', octave: 3 },
            { note: 'G', octave: 3 },
            { note: 'A', octave: 3 },
        ]
    },
];
